### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by reactmore** [codenomdev/midtrans-sample-data#1]
Kak ada sample buat looping item detail gak ? Kan kalo belanja barang gk selalu 1 🙏

**Comment by codenomdev** [comment]
Halo, kak @reactmore .

Pada sample data ini, kamu bisa gunakan Looping Array seperti ini: [Looping Data 1](https://github.com/codenomdev/midtrans-sample-data/blame/8a1e1f1f3009ab7c082d1ed906a60d67d0ab2690/src/Controllers/Vtdirect/Vtdirect.php#L43-L56) atau [Looping Data 2](https://github.com/codenomdev/midtrans-sample-data/blame/8a1e1f1f3009ab7c082d1ed906a60d67d0ab2690/src/Controllers/Snap/Snap.php#L42-L58).

Untuk cara loopingnya , silahkan bisa bertanya diforum ya kak.

**Comment by reactmore** [comment]
iya kak sudah bisa 

```PHP
// Get data cart from sess
if (!empty($cart_items)) {
    foreach ($cart_items as $item) {
        $item_details[] = array(
            'id'        => $item->cart_item_id,
            'price'     => get_price($item->total_price + $item->shipping_cost, 'decimal'),
            'quantity'  => $item->quantity,
            'name'      => $item->product_title,
        );
    }
}
```

**Comment by codenomdev** [comment]
Halo, kak @reactmore.

Bagus, untuk informasi lebih lengkap bisa explore dokumentasi officalnya ya di: [https://docs.midtrans.com/](https://docs.midtrans.com/)

atau jika ada issue, jangan sungkan hubungi kami di: 

1. Issue Sample Data
https://github.com/codenomdev/midtrans-sample-data/issues
2. Issue Midtrans CodeIgniter 4
https://github.com/codenomdev/codeigniter4-midtrans/issues

Issue ini kami tutup ya,

Terima kasih.
